services:
  backend:
    build: ./backend
    container_name: trade-journal-backend
    env_file:
      - ./backend/.env
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: trade-journal-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trade_journal
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: trade-journal-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  inference-server:
    build: ./inference-server
    container_name: trade-journal-inference-server
    ports:
      - "8001:8001"
    restart: unless-stopped

  #  alphavantage:
#    image: ghcr.io/calvernaz/alphavantage:1.0.0
#    container_name: trade-journal-alphavantage
#    env_file:
#      - ./backend/.env
#    ports:
#      - "8002:8000"
#    restart: unless-stopped
