ALTER TABLE trades
  ADD COLUMN IF NOT EXISTS type VARCHAR,
  ADD COLUMN IF NOT EXISTS ticker VARCHAR,
  ADD COLUMN IF NOT EXISTS expiration VARCHAR,
  ADD COLUMN IF NOT EXISTS strike FLOAT,
  ADD COLUMN IF NOT EXISTS option_type VARCHAR;
